---
title: "RaukR project"
subtitle: "Analysis of genomic array data from 9 dog breeds"
author: Cátia Pereira, Dovilė Sinkevičiūtė, Minna Sivonen and Svandís Sæmundsdóttir
date: "`r format(Sys.Date(),format='%d/%m/%Y')`"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: false
    theme: flatly
    highlight: kate
    df_print: paged
    code_folding: hide
    self_contained: false
    keep_md: false
    encoding: "UTF-8"
    css: ["assets/lab.css"]
---

```{r include=FALSE}
## Load packages to use for the data analysis
library(tidyr)
library(dplyr)
library(ggplot2)
library(GenABEL)

# Load the data
load("geno_data_raw.rdat")
```


# Description of the dataset

## Nine dog breeds from five different European countries were analysed in this study.{.tabset}
```{r include=FALSE}
length(unique(data_raw@phdata$Country)) ## data from 5 countries
length(unique(data_raw@phdata$Breed)) ## data covers 9 dog breeds
```
### Dog breeds
```{r}
Abbr <- unique(data_raw@phdata$Breed)
Breed_name <- c("German Shepperd", "Belgian Shepperd", "Labrador retriever", "Finnish lapphund", "Newfoundland", "Dachshund", "Cavalier King Charles spaniel", "Boxer", "Doberman pinscher")

data.frame(Breed_name, Abbr)

```
### Countries
```{r}
unique(data_raw@phdata$Country)
```



## Distribution of breeds by country
```{r}
data_raw@phdata %>%
  group_by(Breed, Country) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  arrange(desc(Country))
```

## Table with the mean age and weight of the dogs, taking sex into account
```{r}
# mean ans sd functions
funm <- function(x){mean(x, na.rm = T)}
funsd <- function(y){sd(y, na.rm = T)}

#table
data_raw@phdata %>%
  group_by(Breed, sex) %>%
  summarize(n = n(),
            meanAge = funm(Age), meanAgeSD = funsd(Age), 
            meanWeight = funm(Body_weight), meanWeightSD = funsd(Body_weight))
```



# Weight distribution for all breeds
```{r}
data_raw@phdata %>% 
    dplyr::select(Breed, Body_weight) %>% 
    na.omit() %>% 
    ggplot(aes(x=Breed, y=Body_weight, fill=Breed)) +
    geom_boxplot() +
    geom_jitter(width = 0.2, alpha=0.3) +
    labs(title="Weight distribution for all breeds",
         subtitle="RaukR project 2019",
         caption="Sources: PLoS ONE, 2015")+
    theme_bw() + 
    scale_fill_manual(values = c("black", "dodgerblue4", "bisque4", "darkgreen","yellow3", "darkgoldenrod3", "darkorchid4", "darkred", "grey"))+
    theme(legend.position = "none")
```

# Principal Component Analysis
```{r}
# Find marker for PCA analysis
# qc0 <- check.marker(data_raw, call = 0.95, perid.call=0.95,
#                     maf=1e-06, p.lev=1e-08, ibs.exclude="lower")
# # Save output from check.marker
# data.qc0 <- data_raw[qc0$idok, qc0$snpok]
# 
# # Remove chromosome 39 (X) from dataset
# autosomalMarkerNames <- snpnames(data.qc0)[chromosome(data.qc0) != 39]
# # Compute genomic kinship matrix
# data.qc0.gkin <- ibs(data.qc0[, autosomalMarkerNames], weight = "freq")
# # Transform it to a distance matrix
# data.qc0.dist <- as.dist(0.5 - data.qc0.gkin)
# # Perform multidimensional scaling to display individuals on a 2D
# # plot preserving genomic distances between them
# data.qc0.mds <- cmdscale(data.qc0.dist)
# # Save the results so no need to run every single time
# pca_result <- save(data.qc0.mds, file="pca_results.rdat")
# Plot the result
load("pca_results.rdat")
df_data_raw <- data.frame(Dim_1 = data.qc0.mds[,1], Dim_2 = data.qc0.mds[,2], Breed= data_raw@phdata$Breed)
ggplot(df_data_raw, aes(Dim_1, Dim_2, color=Breed)) + 
  geom_point(alpha = 0.8) + 
  labs(title="Principal Component Analysis",
       subtitle="RaukR project 2019") +
  theme_bw() +
  scale_color_manual(values = c("black", "dodgerblue4", "bisque4", "darkgreen","yellow3", "darkgoldenrod3", "darkorchid4", "darkred", "grey")) 
```



