---
title: "RaukR project"
subtitle: "Analysis of genomic array data from 9 dog breeds"
author: Cátia Pereira, Dovilė Sinkevičiūtė, Minna Sivonen and Svandís Sæmundsdóttir
date: "`r format(Sys.Date(),format='%d/%m/%Y')`"
output:
  rmarkdown::html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: false
    theme: flatly
    highlight: kate
    df_print: paged
    code_folding: hide
    self_contained: false
    keep_md: false
    encoding: "UTF-8"
    css: ["assets/lab.css"]
---

```{r include=FALSE}
## Load packages to use for the data analysis
library(tidyr)
library(dplyr)
library(ggplot2)
library(GenABEL)
library(maps)
library(tidyverse)
library(purrr)
library(cowplot)
library(ggmap)
library(mapproj)


# Load the data
load("geno_data_raw.rdat")
```

## Distributions of Individuals by Country{.tabset}

### Table

```{r}
country_info <- data_raw@phdata %>% 
  group_by(Country) %>%
  summarize(total_dogs = sum(n())) %>%
  arrange(desc(total_dogs))

country_info$fullname <- c("Finland", "Belgium", "Sweden", "France", "Denmark") 
colnames(country_info)<- c("Abbreviation", "Total number of dogs", "Country")
country_info[,c("Country", "Abbreviation", "Total number of dogs")]

```

### Map

```{r include=FALSE}
europe.map <- get_stamenmap(c(left = -25.410724, bottom = 35.479777,
                              right = 35.618354, top = 71.280356), zoom = 5)
places <- tibble(
  location = c("Sweden",
               "France",
               "Finland", 
               "Denmark",
               "Belgium"),
  lon = c(18.063240, 2.349014, 24.945831, 12.568337, 4.402771),
  lat = c(59.334591, 48.864716, 60.192059, 55.676098, 51.260197))

```

```{r}
ggmap(europe.map) +
  geom_point(aes(x = 18.063240, y = 59.334591), color = 'white', size = 6.6) + #Sweden
  geom_point(aes(x = 2.349014, y = 48.864716), color = 'white', size = 5.3) + #France
  geom_point(aes(x = 24.945831, y = 60.192059), color = 'white', size = 7.1) + #Finland
  geom_point(aes(x = 11.568337, y = 55.676098), color = 'white', size = 5.2) + #Denmark
  geom_point(aes(x = 4.402771, y = 51.260197), color = 'white', size = 7) #Belgium
```

## Distributions of Breeds by Country {.tabset}

```{r include=FALSE}
breeds.country <- data_raw@phdata %>%
  group_by(Breed, Country) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) %>%
  arrange(desc(Country))
```

### Sweden

```{r}
sweden <- subset(breeds.country, breeds.country$Country == 'Swe')
sweden$Country <- NULL
sweden
```

### France

```{r}
france <- subset(breeds.country, breeds.country$Country == 'Fra')
france$Country <- NULL
france
```

### Finland

```{r}
finland <- subset(breeds.country, breeds.country$Country == 'Fin')
finland$Country <- NULL
finland
```

### Denmark

```{r}
denmark <- subset(breeds.country, breeds.country$Country == 'Den')
denmark$Country <- NULL
denmark
```

### Belgium

```{r}
belgium <- subset(breeds.country, breeds.country$Country == 'Bel')
belgium$Country <- NULL
belgium
```

## Map

```{r include=FALSE}
europe.map <- get_stamenmap(c(left = -25.410724, bottom = 35.479777,
                              right = 35.618354, top = 71.280356), zoom = 5)
ggmap(europe.map)

europe.map.complete <- ggmap(europe.map) +
  annotate('rect', xmin=14, ymin=61.5, xmax=16, ymax=62.5, col='white', fill='white') +
  annotate('rect', xmin=2, ymin=47.5, xmax=4, ymax=48.5, col='white', fill='white') +
  annotate('rect', xmin=26, ymin=64.5, xmax=28, ymax=65.5, col='white', fill='white') +
  annotate('rect', xmin=8.5, ymin=55.5, xmax=10.5, ymax=56.5, col='white', fill='white') +
  annotate('text', x=15, y= 62, label = 'A', colour='black', size= 4) +
  annotate('rect', xmin=4, ymin=50.5, xmax=6, ymax=51.5, col='white', fill='white') +
  annotate('text', x=3, y= 48, label = 'B', colour='black', size= 4) +
  annotate('text', x=27, y= 65, label = 'C', colour='black', size= 4) +
  annotate('text', x=9.5, y= 56, label = 'D', colour='black', size= 4) +
  annotate('text', x=5, y= 51, label = 'E', colour='black', size= 4) 
  
 europe.map.complete



sweden.plot <- ggplot(sweden, aes(x=Breed, y=n)) +
  geom_col() +
  labs(title="Sweden") +
  theme_bw(base_family="Gidole")+ 
  xlab("Breed") +
  ylab("Individuals") +
  theme(panel.grid.minor=element_blank(),
        panel.grid.major.x=element_blank(),
        panel.grid.major.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        legend.title=element_blank(),
        axis.title=element_text(face="italic"),
        axis.ticks.y=element_blank(),
        axis.ticks.x=element_line(color="grey60"),
        plot.title=element_text(face="bold"),
        plot.caption=element_text(hjust=0,size=8))

france.plot <- ggplot(france, aes(x=Breed, y=n)) +
  geom_col() +
  labs(title="France") +
  theme_bw(base_family="Gidole")+ 
  xlab("Breed") +
  ylab("Individuals") +
  theme(panel.grid.minor=element_blank(),
        panel.grid.major.x=element_blank(),
        panel.grid.major.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        legend.title=element_blank(),
        axis.title=element_text(face="italic"),
        axis.ticks.y=element_blank(),
        axis.ticks.x=element_line(color="grey60"),
        plot.title=element_text(face="bold"),
        plot.caption=element_text(hjust=0,size=8))

finland.plot <- ggplot(finland, aes(x=Breed, y=n)) +
  geom_col() +
  labs(title="Finland") +
  theme_bw(base_family="Gidole")+ 
  xlab("Breed") +
  ylab("Individuals") +
  theme(panel.grid.minor=element_blank(),
        panel.grid.major.x=element_blank(),
        panel.grid.major.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        legend.title=element_blank(),
        axis.title=element_text(face="italic"),
        axis.ticks.y=element_blank(),
        axis.ticks.x=element_line(color="grey60"),
        plot.title=element_text(face="bold"),
        plot.caption=element_text(hjust=0,size=8))

denmark.plot <- ggplot(denmark, aes(x=Breed, y=n)) +
  geom_col() +
  labs(title="Denmark") +
  theme_bw(base_family="Gidole")+ 
  xlab("Breed") +
  ylab("Individuals") +
  theme(panel.grid.minor=element_blank(),
        panel.grid.major.x=element_blank(),
        panel.grid.major.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        legend.title=element_blank(),
        axis.title=element_text(face="italic"),
        axis.ticks.y=element_blank(),
        axis.ticks.x=element_line(color="grey60"),
        plot.title=element_text(face="bold"),
        plot.caption=element_text(hjust=0,size=8))

belgium.plot <- ggplot(belgium, aes(x=Breed, y=n)) +
  geom_col() +
  labs(title="Belgium") +
  theme_bw(base_family="Gidole")+ 
  xlab("Breed") +
  ylab("Individuals") +
  theme(panel.grid.minor=element_blank(),
        panel.grid.major.x=element_blank(),
        panel.grid.major.y=element_blank(),
        panel.background=element_blank(),
        panel.border=element_blank(),
        legend.title=element_blank(),
        axis.title=element_text(face="italic"),
        axis.ticks.y=element_blank(),
        axis.ticks.x=element_line(color="grey60"),
        plot.title=element_text(face="bold"),
        plot.caption=element_text(hjust=0,size=8))
      
breed.country.plot <- plot_grid(sweden.plot, france.plot, finland.plot, denmark.plot, belgium.plot, labels = c("A", "B", "C", "D", "E"), ncol = 2)

```

```{r}
ggdraw(xlim=c(0,2.3), ylim = c(0,1)) +
  draw_plot(europe.map.complete, x=0.05, y=0, scale=1.2) +
  draw_plot(breed.country.plot, x=1.2, y=0, scale=0.9) 
```

